aftermid/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_6.urls')),
    path('story7/', include('story_7.urls')),
    path('story8/', include('story_8.urls')),
    path('story9/', include('story_9.urls')),
    path('story10/', include('story_10.urls'))
]

story_10/urls.py
from django.urls import path, include
from . import views

app_name = 'story_10'
urlpatterns = [
    path('', views.loadbal_view, name='load_balancer'),
]

story_6/urls.py
from django.urls import path
from . import views

app_name = "story_6"
urlpatterns = [
    path('', views.daftar_status, name="view_form")
]

story_7/urls.py
from django.urls import path
from . import views

app_name = 'story_7'
urlpatterns = [
    path('', views.home, name='landing_accord')
]

story_8/urls.py
from django.urls import path
from . import views

app_name = 'story_8'
urlpatterns = [
    path('', views.home, name='landing_ajax')
]

story_9/urls.py
from django.urls import path, include
from . import views

app_name = 'story_9'
urlpatterns = [
    path('', views.restricted_view, name='landing_cookie'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

story_10/models.py
from django.db import models

# Create your models here.

story_6/models.py
from django.db import models

class Status(models.Model):
    status_inputan = models.CharField(max_length = 300)
    date_created = models.DateTimeField(auto_now_add = True)
    
    def __str__(self):
        return self.status_inputan

story_7/models.py
from django.db import models

# Create your models here.

story_8/models.py
from django.db import models

# Create your models here.

story_9/models.py
from django.db import models

# Create your models here.

story_6/forms.py
from django import forms
from . import models

class BuatStatus(forms.ModelForm):
    class Meta:
        model = models.Status
        fields = ['status_inputan']

story_9/forms.py
from django import forms
from django.forms.widgets import PasswordInput
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Please enter your name')
    last_name = forms.CharField(max_length=30, required=False, help_text='Please enter your name')
    email = forms.EmailField(max_length=254, help_text='Please type your email address')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=30, required=True, help_text='Please enter your username')
    password = forms.CharField(max_length=30, required=True, help_text='Please enter your password', widget=PasswordInput)

story_10/views.py
from django.shortcuts import render

def loadbal_view(request):
    return render(request, "load_bal.html")

story_6/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import Status

def daftar_status(request):
    if request.method == 'POST':
        form = forms.BuatStatus(request.POST)
        if form.is_valid():
            form.save()
            return redirect ('story_6:view_form')
    else:
        form = forms.BuatStatus()

    daftar_status = Status.objects.all().order_by('-date_created')
    return render(request, "landing_page.html", {'semua_status':daftar_status, 'form':form})

story_7/views.py
from django.shortcuts import render

def home(request):
    return render(request, "javas.html")

story_8/views.py
from django.shortcuts import render

def home(request):
    return render(request, "ajax_json.html")

story_9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from story_9.forms import RegisterForm, LoginForm

def register_view(request):
    if request.method == 'POST':
        form_regis = RegisterForm(request.POST)
        if form_regis.is_valid():
            form_regis.save()
            username = form_regis.cleaned_data.get('username')
            raw_password = form_regis.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/story9/')
    else:
        form_regis = RegisterForm()
    return render(request, "register.html", {'form': form_regis})

def login_view(request):
    if request.user.is_authenticated:
        return redirect('/story9/')
    else:
        form = LoginForm()
        if request.method == "POST":
            form = LoginForm(request=request,data=request.POST)
            if form.is_valid():
                user = form.get_user()
                login(request,user=user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                return redirect('/story9/')
            else:
                return render(request, "login.html", {'form': form})
        return render(request, "login.html", {'form': form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('/story9/login/')
    return HttpResponse()

@login_required(login_url='/story9/login')
def restricted_view(request):
    return render(request, "restricted.html")

story_10/templates/load_bal.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Story 10{% endblock title %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/loadbal_style.css' %}">

<div id="content_box">
    <h1 id="par_item">Load Balancer</h1>
    <p id="par_item">
        Pada zaman sekarang, tentunya banyak orang yang sudah "terkoneksi" dengan internet. Melihat suatu website sudah menjadi makanan sehari-hari generasi masa kini. Website tersebut biasanya digunakan untuk memenuhi kebutuhan hidup, berinteraksi atau bersosialisasi, mendapatkan hiburan, atau hal-hal lainnya yang dapat dilakukan secara daring (online). Website-website tersebut tentunya tidak hanya di-request oleh anda saja. Boleh jadi pada detik yang sama terdapat seratus ribu orang seperti anda yang sedang mengakses website yang sama. Meskipun server menerima request sebanyak itu, mengapa server website tersebut tidak down?
    </p>

    <p id="par_item">
        Salah satu alasan server tersebut tidak down adalah adanya "load balancer". Makhluk apakah itu? Singkatnya, load balancer adalah suatu perangkat yang dapat yang berperan sebagai reverse proxy dan membagi beban kerja ke beberapa server. Untuk mempermudah pemahaman, anda dapat membayangkan diri anda menjadi salah satu pengemudi yang hendak mencari tempat parkir. Kemudian, untuk mempermudah anda menemukan tempat parkir, datanglah seorang tukang parkir yang dengan sigap menunjukkan anda harus parkir di suatu parking lot yang tentunya parking lot tersebut kosong. Pada analogi ini, tukang parkir adalah load balancer, pengemudi (anda) adalah orang yang melakukan request ke load balancer, sedangkan parking lot adalah server-server. Jadi, dapat disimpulkan bahwa load balancer salah satunya bertugas untuk mencari server mana yang sedang "kosong" yang kemudian dapat digunakan untuk melayani request user. Jika salah satu server mati pun, load balancer akan membagi beban kerja dari server yang mati ke server yang hidup.
    </p>

    <p id="par_item">
        Pada kesempatan kali ini, saya juga akan menunjukkan bagaimana cara kerja suatu load balancer menggunakan django dan nginx. Untuk membuat sebuah load balancer, anda hanya perlu mengunduh (download) nginx dari website resmi nginx (http://nginx.org/en/download.html). Kemudian setelah selesai mengunduh, maka extract folder tersebut di manapun anda inginkan. Setelah extract selesai, bukalah folder dengan nama "conf" dan temukanlah suatu file bernama "nginx.conf". Kemudian ubahlah isi dalam http menjadi seperti ini.
    </p>

    <img src="{% static 'images/conf_nginx.png' %}" width="400vw">

    <p id="par_item">
        Setelah itu, jalankan nginx dengan membuka command prompt dan ketikkan start nginx. Setelah itu, jalankan server-server django dengan mengetikkan port yang telah didefinisikan pada upstream backend (dalam hal ini 8000 dan 9000). Contoh dari syntaxnya : python manage.py runserver 8000. Kemudian bukalah suatu command prompt baru dan ketikkan python manage.py runserver 9000. Hasilnya akan menjadi seperti ini:
    </p>

    <img src="{% static 'images/runserver.JPG' %}" width="900vw">

    <p id="par_item">
        Setelah itu, pada browser coba ketikkan "localhost" dan refresh berkali-kali halaman websitenya. Selain itu, cobalah untuk mematikan salah satu server kemudian refresh kembali. Berikut ini saya lampirkan hasil uji coba tersebut:
    </p>

    <img src="{% static 'images/nyaladua.JPG' %}" width="900vw">
    <p id="par_item">Terjadi perbedaan server yang melayani request http dengan static</p>

    <img src="{% static 'images/mati8000.JPG' %}" width="900vw">
    <p id="par_item">Halaman tetap dapat diakses meskipun salah satu server dengan port 8000 dimatikan</p>

    <img src="{% static 'images/mati9000.JPG' %}" width="900vw">
    <p id="par_item">Halaman tetap dapat diakses meskipun salah satu server dengan port 9000 dimatikan</p>

    <p id="par_item">
        Dari sini, dapat disimpulkan bahwa load balancer akan mencari server yang masih available dan apabila keduanya available, maka load balancer akan mengarahkan request ke kedua server tersebut secara bergantian.
    </p>

    <p id="par_item">
        Kemudian untuk mematikan load balancer (dalam hal ini nginx), anda dapat mengetikkan perintah ini:
    </p>

    <img src="{% static 'images/matinginx.JPG' %}" width="450vw">
    <p id="par_item">nginx -s stop untuk mematikan load balancer</p>
    
    <p id="par_item">
        Demikian yang dapat saya sampaikan mengenai load balancer. Apabila ada kekurangan atau kesalahan dalam tulisan ini, saya memohon maaf dan terima kasih telah membaca.
    </p>
</div>
{% endblock content %}

story_6/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en"></html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}{% endblock %} - Evando's Aftermid Story</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Evando's Story</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% with url_name=request.resolver_match.url_name %}
                <li class="nav-item">
                    <a class="nav-link {% if url_name == 'view_form' %} active {% endif %}" href="{% url 'story_6:view_form' %}">Story 6<span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if url_name == 'landing_accord' %} active {% endif %}" href="{% url 'story_7:landing_accord' %}">Story 7</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if url_name == 'landing_ajax' %} active {% endif %}" href="{% url 'story_8:landing_ajax' %}">Story 8</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if url_name == 'landing_cookie' %} active {% endif %}" href="{% url 'story_9:landing_cookie' %}">Story 9</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if url_name == 'load_balancer' %} active {% endif %}" href="{% url 'story_10:load_balancer' %}">Story 10</a>
                </li>
                {% endwith %}
            </ul>
        </div>
    </nav>
    {% block content %}{% endblock %}
    
    <div class="footer">
        <p id="footer-item">Sebuah Story PPW</p>
    </div>
    
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

story_6/templates/landing_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Landing Page{% endblock title %}

{% block content %}
<h1 id="welcome_text">Halo, apa kabar?</h1>

<!-- Form untuk menginput status -->
<div class="container">
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <h5 class="card-header header-form">Tambah Status</h5>
            <div class="card-body">
                <form action="" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <div class="form-group" id="form_input">
                        {{ form.status_inputan }}
                    </div>
                    <button type="submit" class="btn btn-light" id="btn_submit">Tambah Status</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Daftar status yang telah ada -->
{% if semua_status %}
<div class="row">
    {% for tiap_status in semua_status %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <p class="card-text" id="form_output">{{ tiap_status.status_inputan }}</p>
            <p class="card-text" id="date_created">{{ tiap_status.date_created }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
    <h1>Belum ada Status</h1>
{% endif %}
{% endblock content %}

story_7/templates/javas.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Story 7{% endblock title %}

{% block content %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="{% static 'css/theme.css' %}" id="theme_css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'js/change-theme.js' %}"></script>

<div class="container-fluid">
    <h3>Change Theme
        <label class="switch">
            <input type="checkbox">
            <span class="slider round"></span>
        </label>
    </h3>

    <div id="accordion">
        <h3 class="accord-header">Aktivitas</h3>
        <div class="accord-content">
            <p>
                Code. Rapat. Eat. Sleep. Repeat
            </p>
        </div>
        
        <h3 class="accord-header">Pengalaman Organisasi / Kepanitiaan</h3>
        <div class="accord-content">
            <p>
                <ul>
                    <li>OSIS SMA Marsudirini Bekasi</li>
                    <ol>
                        <li>Seksi Kehidupan Berbangsa dan Bernegara (2016)</li>
                        <li>Bendahara 1 (2017)</li>
                    </ol>
                    <li>Misdinar Santo Bartolomeus</li>
                    <ol>
                        <li>Wakil Ketua (2016)</li>
                    </ol>
                    <li>Pemira Fasilkom UI</li>
                    <ol>
                        <li>Staf Divisi Pemungutan Suara (2018)</li>
                    </ol>
                    <li>Computer's Get Together</li>
                    <ol>
                        <li>Staf Divisi Bazaar dan Konsumsi (2018)</li>
                    </ol>
                    <li>BEM Fasilkom UI</li>
                    <ol>
                        <li>Staf Departemen Adkesma (2019)</li>
                    </ol>
                    <li>Compfest 11</li>
                    <ol>
                        <li>Staf Divisi Playground (2019)</li>
                    </ol>
                    <li>Open House Fasilkom UI</li>
                    <ol>
                        <li>Bendahara (2019)</li>
                    </ol>
                    <li>Educare</li>
                    <ol>
                        <li>Bendahara (2020)</li>
                    </ol>
                </ul>
            </p>
        </div>

        <h3 class="accord-header">Prestasi</h3>
        <div class="accord-content">
            <p>
                <ul>
                    <li>Juara III Wild games tingkat SMP</li>
                    <ul>
                        <li>lomba tentang ilmu pengetahuan alam yang diselenggarakan oleh SMAN 1 Bekasi</li>
                    </ul>
                </ul>
            </p>
        </div>
    </div>
</div>
{% endblock content %}

story_8/templates/ajax_json.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Story 8{% endblock title %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/ajax_style.css' %}" id="theme_css" />
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'js/ajax_jquery.js' %}"></script>

<div class="container-fluid header">
    <h1>Book Seeker</h1>
</div>

<div class="container-fluid search-box">
    <div class="ui-widget">        
        <input type="text" id="search-box-input" placeholder="Search..">
    </div>
    <button type="button" id="search-button"><i class="fa fa-search"></i></button>
</div>

<div class="container-fluid book-display">
    <div class="table-responsive">
        <table class="table table-striped" id="buku-ini"></table>
    </div>
</div>
{% endblock content %}

story_9/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Story 9{% endblock title %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/authcook_style.css' %}" id="theme_css" />
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<div class="container-fluid header">
    <h1>Story 9</h1>
</div>

<div class="container-fluid">
    <div class="row regisbackground">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h4>Login, Let's Go!</h4>
            <form action="{% url 'story_9:login' %}" method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" id="btn_login" type="submit">Login</button>
                </div>
            </form>
            <p>Didn't have an account? <a href="{% url 'story_9:register' %}">Register Now</a></p>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock content %}

story_9/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Story 9{% endblock title %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/authcook_style.css' %}" id="theme_css" />
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<div class="container-fluid header">
    <h1>Story 9</h1>
</div>

<div class="container-fluid">
    <div class="row regisbackground">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h4>Register Now</h4>
            <form action="{% url 'story_9:register' %}" method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                    </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Sign Up</button>
                </div>
            </form>
            <p>Already have an account? <a href="{% url 'story_9:login' %}">Login</a></p>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock content %}

story_9/templates/restricted.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Story 9{% endblock title %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/authcook_style.css' %}" id="theme_css" />
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<div class="container-fluid header">
    <h1>Story 9</h1>
</div>

<div class="container-fluid">
    <div class="row regisbackground">
        <div class="col-md-3"></div>

        <div class="col-md-6">
            <h3>Welcome, {{ user }}</h3>
            <img src="{% static 'img/easter_egg.jpg' %}">
            <p>Jutaan orang bahkan tidak menyadari bahwa mereka bisa menghasilkan $1000 sehari tanpa meninggalkan rumah dan anda adalah salah satu dari mereka</p>
            <form action="{% url 'story_9:logout' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-outline-info" id="btn_logout" type="submit">Logout</button>
            </form>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock content %}